# Configuration for KOMOE static site generator.

komoe_require = '0.4.0'

[project]
name = 'Birdway'

[build]
source = 'source'
templates = 'templates'
static = 'static'
output = 'site'

[plugin.sass]
package = "komoe_sass"
config.path = "style"
config.command = "npx sass {input} {output}"

[plugin.bw]
script = "bw-plugin.py"
