def transpile(ast, **kwargs):
    code = "/*=== GENERATED BY BIRDWAY A-5966d ===*/\n#include <stdio.h>\n"
    code += transpile_string_constants(ast, kwargs)
    return code


def transpile_string_constants(ast, kwargs):
    return f'char[] BIRDWAY_APPLICATION_IDENTIFICATION = "{kwargs.get("name", "[unnamed]")} version [unspecified]";'
